### ISSUE TITLE
Update governance docs with new information from 6/25/15 DGAB meeting

### ISSUE THREAD

**Issue by theadactyl** [docker/opensource#12]
Update docs to reflect new membership and working groups resulting from newest DGAB meeting: https://github.com/docker/opensource/blob/master/docs/governance/board-profiles.md

**Comment by thaJeztah** [comment]
Think this is resolved by https://github.com/docker/opensource/pull/15?

**Comment by thaJeztah** [comment]
O, hi @theadactyl :smiley:
