### ISSUE TITLE
Website issue ::bug::

### ISSUE THREAD

**Issue by I-Cat** [docker/opensource#124]
https://www.docker.com/get-started

I coudent edit the web site so I made an issue here as there is no issue page for docker.com
Tnx

Problem, I went to the site to see the developer page
The page links to get-started instead

![image](https://user-images.githubusercontent.com/68921721/106088957-eda17400-60f4-11eb-8ed2-486ba6705167.png)

@thaJeztah

**Comment by thaJeztah** [comment]
Thanks for reporting; I'll check with the marketing team (who maintains the website), but this _may be_ the intended location (the getting started is used as an introduction to docker for developers that want to use docker for their development).

Is it possible you have JavaScript disabled in your browser? As there should be a pop-up menu when you hover over the `Developers` menu item, which shows other pages as well ("get started" is the first item in that list);

<img width="337" alt="Screenshot 2021-01-28 at 14 39 45" src="https://user-images.githubusercontent.com/1804568/106146636-339f1c00-6177-11eb-9f6d-57f36a0842a7.png">


/cc @pmckeetx @williamquiviger

**Comment by I-Cat** [comment]
nope your web site code is wrong ,I can't fix it from here but I can show you the source code that is stopping this


It is here

      
            <div><div id="consent_blackbar"></div>
<div id="teconsent"></div>
<script async="async" src="https://consent.truste.com/notice?domain=docker.com&c=teconsent&js=bb&noticeType=bb"></script></div>
      
  </div>
<div id="block-mouseflow">
  
    
      
            <div><script type="text/javascript">
    window._mfq = window._mfq || [];
    (function() {
        var mf = document.createElement("script");
        mf.type = "text/javascript"; mf.async = true;
        mf.src = "//cdn.mouseflow.com/projects/6f7d6de3-deb5-4950-9ff2-e178439823d6.js";
        document.getElementsByTagName("head")[0].appendChild(mf);
    })();
</script></div>
      
  </div>

  </div>

            </div>
        </footer>
            </div>
    
      </body>
</html>

**Comment by thaJeztah** [comment]
If it's the mouseflow code, probably something that's injected by google tag manager

**Comment by I-Cat** [comment]
> If it's the mouseflow code, probably something that's injected by google tag manager

@thaJeztah  Okay And I Cannot Run Docker on my Windows 10 Home addition
Do you think it is possable to include all of the requirements in the install .exe file instead of Tryingto add it all on your own. ?

example

script , powershell.ps1
echo on
run ps script [ for wsl ]
run docker.install.exe
yada yada ? 😄

**Comment by I-Cat** [comment]
tnx
