### ISSUE TITLE
Create a "project" template directory

### ISSUE THREAD

**Issue by thaJeztah** [docker/opensource#44]
Create a directory containing all documents and instructions on how to setup a new repository;

- standard LICENSE and NOTICE
- CONTRIBUTING.md (including DCO instructions)
- instructions how to set up  DCO check
- MAINTAINERS file
- CI config (and instructions)

**Comment by thaJeztah** [comment]
Probably also a description of our standard "labels"

**Comment by icecrime** [comment]
:+1:

**Comment by tiborvass** [comment]
:+1:
